### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.jsp.jstl.core.ConditionalTagSupport

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [jakartaee/pages#243]
Hi,

After Upgrading from 3.0.0 to 3.0.1. 

<groupId>org.glassfish.web</groupId>
<artifactId>jakarta.servlet.jsp.jstl</artifactId>

We are getting the below issues.

Caused by: java.lang.ClassNotFoundException: jakarta.servlet.jsp.jstl.core.ConditionalTagSupport
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]

**Comment by pzygielo** [comment]
- https://github.com/jakartaee/tags/issues/248
